services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: telegram
      POSTGRES_PASSWORD: telegram
      POSTGRES_DB: telegram_mini_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
